FROM ubuntu:latest

RUN mkdir -p /app

WORKDIR /app

COPY . /app

RUN apt-get -y update && \
apt-get -y install python3 python3-pip && \
pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD FLASK_APP=start.py flask run